//! On-disk format compatibility with older releases.
//!
//! jjj's metadata is markdown-with-frontmatter in a jj bookmark. Users upgrade
//! the binary; they do not migrate their repository. So every field a past
//! release wrote must still load — and the schema has moved: `force_accepted`
//! became `force_approved`, five free-form fields (`context`, `tradeoffs`,
//! `evidence`, `goals`, `success_criteria`) were folded into the body, and the
//! relational back-references (`solution_ids`, `critique_ids`, `problem_ids`,
//! `child_ids`) stopped being stored and became derived.
//!
//! The corpora under `tests/fixtures/corpus-*` were generated by *actually
//! building* the release in question and running it — not hand-written to match
//! what we remember the schema being, which would test our memory rather than
//! the format. Regenerate with the recipe in `tests/fixtures/README.md`.

mod test_helpers;

use std::fs;
use std::path::{Path, PathBuf};

use test_helpers::{jj_available, run_jjj, run_jjj_success, setup_test_repo};

fn fixture_dir(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

/// Copy a fixture corpus over a freshly-initialized repo's metadata, as an
/// upgrade would find it.
fn repo_from_fixture(name: &str) -> tempfile::TempDir {
    let repo = setup_test_repo();
    let meta = repo.path().join(".jj/jjj-meta");
    let src = fixture_dir(name);
    assert!(
        src.exists(),
        "missing fixture corpus {} — see tests/fixtures/README.md",
        src.display()
    );

    for entry in fs::read_dir(&src).expect("read fixture") {
        let entry = entry.expect("fixture entry");
        let dest = meta.join(entry.file_name());
        if entry.path().is_dir() {
            fs::create_dir_all(&dest).ok();
            for file in fs::read_dir(entry.path()).expect("read fixture subdir") {
                let file = file.expect("fixture file");
                fs::copy(file.path(), dest.join(file.file_name())).expect("copy fixture file");
            }
        } else {
            fs::copy(entry.path(), &dest).expect("copy fixture file");
        }
    }

    drop_derived_cache(repo.path());
    repo
}

/// Remove the SQLite cache so reads come from the canonical markdown.
///
/// An older release's DB carries an older `schema_version` and is rebuilt on
/// first use, so an upgrade always reads the files first. A test that installs
/// entity files behind jjj's back has to do the same: the freshly-initialized
/// DB is empty *and clean*, so leaving it in place makes every read serve zero
/// entities and every assertion fail for the wrong reason.
fn drop_derived_cache(repo: &Path) {
    for suffix in ["", "-wal", "-shm"] {
        let _ = fs::remove_file(repo.join(format!(".jj/jjj.db{suffix}")));
    }
}

/// Every corpus must satisfy the same baseline: it loads, and nothing is lost.
fn assert_corpus_loads(corpus: &str) {
    let repo = repo_from_fixture(corpus);

    let problems = run_jjj_success(repo.path(), &["problem", "list"]);
    assert!(
        problems.contains("Session tokens never expire"),
        "{corpus}: problems did not load:\n{problems}"
    );
    assert!(
        problems.contains("Slow dashboard"),
        "{corpus}: second problem missing:\n{problems}"
    );

    let solutions = run_jjj_success(repo.path(), &["solution", "list"]);
    assert!(
        solutions.contains("Add a 24h TTL"),
        "{corpus}: solutions did not load:\n{solutions}"
    );

    let critiques = run_jjj_success(repo.path(), &["critique", "list"]);
    assert!(
        critiques.contains("Refresh tokens need rotation"),
        "{corpus}: critiques did not load:\n{critiques}"
    );

    let milestones = run_jjj_success(repo.path(), &["milestone", "list"]);
    assert!(
        milestones.contains("v1.0"),
        "{corpus}: milestones did not load:\n{milestones}"
    );
}

#[test]
fn a_0_3_corpus_still_loads() {
    if !jj_available() {
        return;
    }
    assert_corpus_loads("corpus-0.3");
}

#[test]
fn a_0_4_corpus_still_loads() {
    if !jj_available() {
        return;
    }
    assert_corpus_loads("corpus-0.4");
}

#[test]
fn a_0_4_corpus_keeps_its_scalar_fields() {
    if !jj_available() {
        return;
    }
    let repo = repo_from_fixture("corpus-0.4");
    let json = run_jjj_success(repo.path(), &["problem", "list", "--json"]);

    // Priority, status and tags are user-authored data. Silently defaulting any
    // of them on load would look like a working upgrade and quietly rewrite the
    // user's board.
    assert!(
        json.contains("\"priority\": \"critical\""),
        "priority lost: {json}"
    );
    assert!(
        json.contains("\"priority\": \"medium\""),
        "priority lost: {json}"
    );
    assert!(
        json.contains("\"status\": \"in_progress\""),
        "status lost: {json}"
    );
    assert!(json.contains("security"), "tags lost: {json}");
    assert!(json.contains("auth"), "tags lost: {json}");
}

#[test]
fn stored_back_references_still_resolve_after_they_became_derived() {
    if !jj_available() {
        return;
    }
    let repo = repo_from_fixture("corpus-0.4");

    // 0.4 wrote `solution_ids` / `critique_ids` / `problem_ids` into the file.
    // 0.5 derives them from the forward references instead. The old keys are
    // now unknown to the schema, and the relationships must survive anyway —
    // via the `problem_id` / `solution_id` / `milestone_id` on the other side.
    let json = run_jjj_success(repo.path(), &["solution", "list", "--json"]);
    assert!(
        json.contains("problem_id"),
        "the forward reference is what derivation depends on: {json}"
    );

    let shown = run_jjj_success(repo.path(), &["problem", "show", "Session tokens"]);
    assert!(
        shown.contains("Add a 24h TTL"),
        "a solution stored under the old back-reference no longer links to its \
         problem:\n{shown}"
    );

    let milestone = run_jjj_success(repo.path(), &["milestone", "show", "v1.0"]);
    assert!(
        milestone.contains("Slow dashboard"),
        "milestone membership lost on upgrade:\n{milestone}"
    );
}

#[test]
fn an_old_corpus_round_trips_without_losing_fields() {
    if !jj_available() {
        return;
    }
    let repo = repo_from_fixture("corpus-0.4");

    // Editing one entity must not strip fields from it — or from anything else
    // the command happens to rewrite.
    run_jjj_success(
        repo.path(),
        &["problem", "edit", "Slow dashboard", "--priority", "high"],
    );

    let json = run_jjj_success(repo.path(), &["problem", "list", "--json"]);
    assert!(
        json.contains("\"priority\": \"high\""),
        "edit did not apply"
    );
    assert!(
        json.contains("\"priority\": \"critical\""),
        "editing one problem changed another: {json}"
    );

    let after = run_jjj_success(repo.path(), &["problem", "list", "--json"]);
    assert!(after.contains("security"), "tags lost on save: {after}");
}

#[test]
fn the_legacy_force_accepted_key_is_still_accepted() {
    if !jj_available() {
        return;
    }
    let repo = setup_test_repo();

    // The rename shipped with a serde alias. Nothing tested the alias, so a
    // future cleanup could drop it and break every pre-rename repository.
    let id = "01900000-0000-7000-8000-000000000001";
    let problem_id = "01900000-0000-7000-8000-000000000002";
    fs::write(
        repo.path()
            .join(".jj/jjj-meta/problems")
            .join(format!("{problem_id}.md")),
        format!(
            "---\nid: '{problem_id}'\ntitle: Ancient problem\nstatus: open\npriority: medium\n\
             created_at: '2026-01-01T00:00:00Z'\nupdated_at: '2026-01-01T00:00:00Z'\n---\n"
        ),
    )
    .expect("write problem");
    fs::write(
        repo.path()
            .join(".jj/jjj-meta/solutions")
            .join(format!("{id}.md")),
        format!(
            "---\nid: '{id}'\ntitle: Ancient solution\nproblem_id: '{problem_id}'\n\
             status: approved\nforce_accepted: true\ncreated_at: '2026-01-01T00:00:00Z'\n\
             updated_at: '2026-01-01T00:00:00Z'\n---\n"
        ),
    )
    .expect("write solution");
    drop_derived_cache(repo.path());

    let out = run_jjj(repo.path(), &["solution", "list"]);
    let combined = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        combined.contains("Ancient solution"),
        "the force_accepted alias was dropped, breaking pre-rename repos: {combined}"
    );
}

#[test]
fn removed_free_form_fields_do_not_break_loading() {
    if !jj_available() {
        return;
    }
    let repo = setup_test_repo();

    // `context`, `tradeoffs`, `evidence`, `goals` and `success_criteria` were
    // removed in favour of the body. Old files still carry them, and an unknown
    // key must be ignored rather than failing the parse — otherwise upgrading
    // makes the whole repository unreadable.
    let id = "01900000-0000-7000-8000-000000000003";
    fs::write(
        repo.path()
            .join(".jj/jjj-meta/problems")
            .join(format!("{id}.md")),
        format!(
            "---\nid: '{id}'\ntitle: Problem with retired fields\nstatus: open\n\
             priority: high\ncontext: 'Discovered during the incident'\n\
             success_criteria: 'p99 under 200ms'\ngoals:\n- 'Reduce latency'\n\
             created_at: '2026-01-01T00:00:00Z'\nupdated_at: '2026-01-01T00:00:00Z'\n---\n\
             The dashboard is slow.\n"
        ),
    )
    .expect("write problem");
    drop_derived_cache(repo.path());

    let listed = run_jjj_success(repo.path(), &["problem", "list"]);
    assert!(
        listed.contains("Problem with retired fields"),
        "a retired field made the entity unloadable: {listed}"
    );

    let shown = run_jjj_success(repo.path(), &["problem", "show", "retired fields"]);
    assert!(
        shown.contains("The dashboard is slow."),
        "the body should still render: {shown}"
    );
}

#[test]
fn the_cache_can_be_built_from_an_old_corpus() {
    if !jj_available() {
        return;
    }
    let repo = repo_from_fixture("corpus-0.4");

    // The DB is derived, so an upgrade rebuilds it from files written by the
    // older release. A schema mismatch here turns search and status into
    // silently-empty results rather than an error.
    run_jjj_success(repo.path(), &["db", "rebuild"]);

    let searched = run_jjj_success(repo.path(), &["search", "session"]);
    assert!(
        searched.contains("Session tokens never expire"),
        "the rebuilt index does not see the migrated corpus:\n{searched}"
    );
}
